meta_product_name: "Success Deal"
meta_title: "Success Deal | Jonathan Bellaïche"
meta_description: "Success Deal | Conseil en cessions d’entreprise et levées de fonds"
meta_image: "logo_blue.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
